name: New Zone Record
description: "Create a new DNS zone record using Terraform."
questions:
  - prompt: "Firewall rule name"
    variableName: rule_name
    placeholder: "my-firewall-rule"
    required: true
    inputType: textfield
    variableType: string
  - prompt: "Source tags"
    inputType: list
    variableName: source_tags
    required: true
    variableType: list
outputs:
  - templateFile: examples/terraform_gcp_firewall_rule/firewall_rule.tpl
    outputFile: terraform/{{.rule_name}}.tf