name: "contrib"
on:
  issue_comment:
    types: [created]
  pull_request_target:
    types: [opened,closed,synchronize]

# explicitly configure permissions, in case your GITHUB_TOKEN workflow permissions are set to read-only in repository settings
permissions:
  actions: write
  contents: write
  pull-requests: write
  statuses: write

jobs:
  CLAAssistant:
    runs-on: ubuntu-latest
    steps:
      - name: CLA assistant lite
        uses: contributor-assistant/github-action@v2.2.1
        if: (github.event.comment.body == 'recheck' || github.event.comment.body == 'I have read the CLA Document and I hereby sign the CLA') || github.event_name == 'pull_request_target'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # the below token should have repo scope and must be manually added by you in the repository's secret
          # This token is required only if you have configured to store the signatures in a remote repository/organization
          PERSONAL_ACCESS_TOKEN: ${{ secrets.COMMUNITY_GITHUB_TOKEN }}
          with:
            remote-organization-name: "peachpielabs"
            remote-repository-name: "cla"
            path-to-signatures: "v2023-05-14/signatures.json"
            path-to-document: "https://github.com/peachpielabs/cla/blob/main/README.md"
            # branch should not be protected
            branch: "main"
            allowlist: dependabot*

